image: node:14.17.0
pipelines:
  branches:
     dev:
       - step:
           size: 2x
           name: Build & Deploy
           deployment: dev
           script:
              - apt-get update && apt-get install -y awscli
              - aws --version
              - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
              - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
              - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
              - chmod +x build-deploy.sh && bash build-deploy.sh
     master:
       - step:
           size: 2x
           name: Build & Deploy
           deployment: Production
           script:
              - apt-get update && apt-get install -y awscli
              - aws --version
              - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
              - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
              - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
              - chmod +x build-deploy.sh && bash build-deploy.sh

